name: ssl_cert_generator
description: SSL Cert Generator
inputs:
  profile:
    required: true
    type: string
  region:
    required: true
    type: string
  namespace:
    required: true
    type: string
  ofirydevops_dir:
    required: true
    type: string



runs:
  using: composite
  steps:

    - name: Setup Global Conf
      shell: bash
      working-directory: ${{ inputs.ofirydevops_dir }}
      run: |
        ./.github/scripts/setup_global_conf.sh ${{ inputs.profile }} ${{ inputs.region }} ${{ inputs.namespace }}

    - name: Build Docker
      shell: bash
      working-directory: ${{ inputs.ofirydevops_dir }}
      run: docker compose -f deployment/docker/build-ssl.yml build

    - name: Generate SSL Cert
      shell: bash
      working-directory: ${{ inputs.ofirydevops_dir }}
      run: |
          docker compose -f deployment/docker/build-ssl.yml up

