name: batch_runner_test

on:
  workflow_dispatch:

jobs:
  test_batch_runner:
    runs-on: 
      - self-hosted
      - basic_amd64_100GB
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Pipenv Install
        run: pipenv install

      - name: Test Batch Runner
        run: |
            pipenv run python3.10 -m batch_runner.test.test
