name: ssl_certs_generator

on:
  workflow_dispatch:
    inputs:
      domain:
        description: Domain for which to create a wild card ssl cert
        type: choice
        options:
          - ofirydevops.com
          - dev.ofirydevops.com
          - stg.ofirydevops.com
          - sbx.ofirydevops.com
        required: true


jobs:
  generate_ssl_cert:
    runs-on: 
      - self-hosted
      - basic_arm64_100GB
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pipenv Install
        run: pipenv install

      - name: Generate SSL Cert
        run: |
            pipenv run python3.10 -m ssl_certs_creator.renew_ssl_cert --domain ${{ github.event.inputs.domain }}

