name: terraform_projects_mgmt
description: Terraform Projects Management
inputs:
  profile:
    required: true
    type: string
  region:
    required: true
    type: string
  namespace:
    required: true
    type: string
  tf_action:
    required: true
    type: string
  tf_project:
    required: true
    type: string
  ofirydevops_dir:
    required: true
    type: string


runs:
  using: composite
  steps:

    - name: Setup Global Conf
      shell: bash
      working-directory: ${{ inputs.ofirydevops_dir }}
      run: |
        ./.github/scripts/setup_global_conf.sh ${{ inputs.profile }} ${{ inputs.region }} ${{ inputs.namespace }}

    - name: Pipenv Install
      shell: bash
      working-directory: ${{ inputs.ofirydevops_dir }}
      run: pipenv install

    - name: Run Terraform Action
      shell: bash
      working-directory: ${{ inputs.ofirydevops_dir }}
      run: |
          pipenv run python3.10 -m deployment.tf_manager \
                                    --tf-action ${{ inputs.tf_action }} \
                                    --tf-project ${{ inputs.tf_project }}

