name: python_env_job_runner

on:
  workflow_dispatch:
    inputs:
      repository:
        description: Repository
        type: choice
        options: ${repositories}
        default: ${default_repository}
        required: true
      repository_ref:
        description: Repository ref
        type: string
        required: true
        default: main
      repository_py_env_file_path:
        description: Python environment file path
        type: string
        required: true
        default: ${default_py_env_file}
      timeout_in_minutes:
        description: Job timeout in minutes
        type: choice
        options: [10, 20 , 40, 80, 160, 320, 640]
        required: true
      command:
        description: Job run command
        type: string
        required: true
        default: ${default_enterypoint}
      node:
        description: Runner node
        type: choice
        options: ${github_runner_labels}
        required: true


env:
  DOCKER_IMAGE_TAG: $${{ github.run_id }}-$${{ github.run_number }}
  WORKDIR: guest_repo

jobs:
  build_and_run:
    runs-on: 
      - self-hosted
      - $${{ github.event.inputs.node }}
    steps:
      - name: Checkout ofirydevops
        uses: actions/checkout@v4
        with:
          repository: ofirydevops/ofirydevops
          ref: update2

      - name: Setup Global Config
        uses: ofirydevops/ofirydevops/.github/actions/setup_global_conf@update2
        with:
          profile: $${{ vars.MAIN_AWS_PROFILE }}
          region: $${{ vars.MAIN_AWS_REGION }}
          namespace: $${{ vars.NAMESPACE }}

      - name: Checkout Guest Repo
        uses: actions/checkout@v4
        with:
          repository: $${{ github.event.inputs.repository }}
          token: $${{ secrets.OFIRYDEVOPS_GITHUB_TOKEN }}
          ref: $${{ github.event.inputs.repository_ref }}
          path: $${{ env.WORKDIR }}


      - name: Pipenv Install
        run: pipenv install

      - name: Build Python Env Docker
        run: |
            pipenv run python3.10 -u -m python_env_runner.scripts.build_py_env \
                                            --py-env-conf-file $${{ env.WORKDIR }}/$${{ github.event.inputs.repository_py_env_file_path }} \
                                            --docker-image-tag $${{ env.DOCKER_IMAGE_TAG }} \
                                            --target runtime \
                                            --workdir $${{ env.WORKDIR }}

      - name: Run Python Job
        run: |
          TIMEOUT_SECONDS=$(( $${{ github.event.inputs.timeout_in_minutes }} * 60 ))
          timeout $TIMEOUT_SECONDS \
          pipenv run python3.10 -u -m python_env_runner.scripts.run_py_env \
                                        --docker-image-tag $${{ env.DOCKER_IMAGE_TAG }} \
                                        --entrypoint "$${{ github.event.inputs.command }}"
