version: "3.9"
services:
  main:
    network_mode: bridge
    build:
      context: ../../
      dockerfile: ./root_jenkins/docker/Dockerfile
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        DOMAIN: ${DOMAIN}
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_REPO}:${DOCKER_IMAGE_TAG}
    ports:
      # - 443:8443
      - 80:8443
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home:
