name: batch_runner_test

on:
  workflow_dispatch:

jobs:
  batch_runner_test:
    runs-on: 
      - self-hosted
      - basic_amd64_100GB
    steps:
      - name: Test Batch Runner
        uses: ofirydevops/ofirydevops/.github/actions/batch_runner_test@${ofirydevops_ref}
        with:
          profile: $${{ vars.MAIN_AWS_PROFILE }}
          region: $${{ vars.MAIN_AWS_REGION }}
          namespace: $${{ vars.NAMESPACE }}
          ofirydevops_ref: ${ofirydevops_ref}

