name: ssl_cert_generator

on:
  workflow_dispatch:

jobs:
  ssl_cert_generator:
    runs-on: 
      - self-hosted
      - basic_arm64_100GB
    steps:
      - name: Generate SSL Cert
        uses: ofirydevops/ofirydevops/.github/actions/ssl_cert_generator@${ofirydevops_ref}
        with:
          profile: $${{ vars.MAIN_AWS_PROFILE }}
          region: $${{ vars.MAIN_AWS_REGION }}
          namespace: $${{ vars.NAMESPACE }}
          ofirydevops_ref: ${ofirydevops_ref}
