name: ssl_cert_generator

on:
  workflow_dispatch:
    inputs:
      ofirydevops_ref:
        type: string
        required: true
        empty: false
        default: ${ofirydevops_ref}

jobs:
  ssl_cert_generator:
    runs-on: 
      - self-hosted
      - basic_arm64_100GB
    steps:

      - name: Checkout ofirydevops
        uses: actions/checkout@v4
        with:
          repository: ${ofirydevops_repo}
          ref: $${{ inputs.ofirydevops_ref }}
          path: ${ofirydevops_dir}
          token: $${{ secrets.OFIRYDEVOPS_GITHUB_TOKEN }}

      - name: Generate SSL Cert
        uses: ${ofirydevops_dir}/.github/actions/ssl_cert_generator
        with:
          profile: $${{ vars.MAIN_AWS_PROFILE }}
          region: $${{ vars.MAIN_AWS_REGION }}
          namespace: $${{ vars.NAMESPACE }}
          ofirydevops_dir: ${ofirydevops_dir}

