DEFAULT_DOCKER_REGISTRY   = "local"
DEFAULT_DOCKER_IMAGE_REPO = "python-env"
DEFAULT_DOCKER_IMAGE_TAG  = "local"
GLOBAL_CONF_JSON          = "global_conf.json"
DOCKER_COMPOSE_FILE       = "data_science/docker/docker-compose-v2.yml"