version: "3.9"

services:
  main:
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_REPO}:${DOCKER_IMAGE_TAG}
    network_mode: bridge
    build:
      context: ../../
      dockerfile: data_science/docker/Dockerfile
      target: builder
