version: "3.9"

x-image: &image
  image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_REPO}:${DOCKER_IMAGE_TAG}


x-gpu_runtime_build_args: &gpu_runtime_build_args
  RUNTIME_IMAGE: nvidia/cuda:12.8.1-cudnn-runtime-ubuntu22.04

x-cpu_runtime_build_args: &cpu_runtime_build_args
  RUNTIME_IMAGE: ubuntu:22.04

x-build_args: &build_args
  CONDA_ENV_INTERNAL_NAME: main
  CONDA_ENV_FILE_PATH: data_science/conda_envs/${CONDA_ENV}.yaml

x-amd64_build_args: &amd64_build_args
  AWS_CLI_DOWNLOAD_LINK: https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.15.37.zip

x-arm64_build_args: &arm64_build_args
  AWS_CLI_DOWNLOAD_LINK: https://awscli.amazonaws.com/awscli-exe-linux-aarch64-2.15.37.zip

x-build: &build
  context: ../../
  dockerfile: data_science/docker/Dockerfile

x-main_conf: &main_conf
  <<: *image
  network_mode: bridge


x-gpu: &gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

x-remote_dev_ports: &remote_dev_ports
  ports:
    - 5000:22
  

x-cache_to_amd64: &cache_to_amd64
  cache_to:
  - type=registry,ref=${AWS_REGITRY_REF_REPO}:data_science_amd64_${CONDA_ENV},mode=max,image-manifest=true,oci-mediatypes=true
x-cache_to_arm64: &cache_to_arm64
  cache_to:
  - type=registry,ref=${AWS_REGITRY_REF_REPO}:data_science_arm64_${CONDA_ENV},mode=max,image-manifest=true,oci-mediatypes=true

x-cache_from_amd64: &cache_from_amd64
  cache_from:
  - type=registry,ref=${AWS_REGITRY_REF_REPO}:data_science_amd64_${CONDA_ENV}
x-cache_from_arm64: &cache_from_arm64
  cache_from:
  - type=registry,ref=${AWS_REGITRY_REF_REPO}:data_science_arm64_${CONDA_ENV}


services:
  main_arm64:
    <<: *main_conf
    platform: linux/arm64
    build:
      <<: [*build, *cache_from_arm64]
      target: runtime
      args:
        <<: [*build_args, *arm64_build_args, *cpu_runtime_build_args]

  main_amd64:
    <<: *main_conf
    build:
      <<: [*build, *cache_from_amd64]
      target: runtime
      args:
        <<: [*build_args, *amd64_build_args, *cpu_runtime_build_args]

  main_arm64_gpu:
    <<: [*main_conf, *gpu]
    platform: linux/arm64
    build:
      <<: [*build, *cache_from_arm64]
      target: runtime
      args:
        <<: [*build_args, *arm64_build_args, *gpu_runtime_build_args]

  main_amd64_gpu:
    <<: [*main_conf, *gpu] 
    build:
      <<: [*build, *cache_from_amd64]
      target: runtime
      args:
        <<: [*build_args, *amd64_build_args, *gpu_runtime_build_args]

  main_amd64_update_cache:
    <<: *main_conf
    build:
      <<: [*build, *cache_from_amd64, *cache_to_amd64]
      target: runtime
      args:
        <<: [*build_args, *amd64_build_args, *cpu_runtime_build_args]

  main_arm64_update_cache:
    <<: *main_conf
    platform: linux/arm64
    build:
      <<: [*build, *cache_from_arm64, *cache_to_arm64, *cpu_runtime_build_args]
      target: runtime
      args:
        <<: [*build_args, *amd64_build_args]

  remote_dev_amd64:
    <<: [*main_conf, *remote_dev_ports] 
    build:
      <<: [*build, *cache_from_amd64]
      target: remote_dev
      args:
        <<: [*build_args, *amd64_build_args, *cpu_runtime_build_args]

  remote_dev_arm64:
    <<: [*main_conf, *remote_dev_ports]
    platform: linux/arm64
    build:
      <<: [*build, *cache_from_arm64]
      target: remote_dev
      args:
        <<: [*build_args, *arm64_build_args, *cpu_runtime_build_args]


  remote_dev_amd64_gpu:
    <<: [*main_conf, *gpu, *remote_dev_ports]
    build:
      <<: [*build, *cache_from_amd64]
      target: remote_dev
      args:
        <<: [*build_args, *amd64_build_args, *gpu_runtime_build_args]

  remote_dev_arm64_gpu:
    <<: [*main_conf, *gpu, *remote_dev_ports]
    platform: linux/arm64
    build:
      <<: [*build, *cache_from_arm64]
      target: remote_dev
      args:
        <<: [*build_args, *arm64_build_args, *gpu_runtime_build_args]