name: main_workflow

on:
  workflow_dispatch:
    inputs:
      myinput:
        type: string
        description: My Input
        required: true


jobs:
  test:
    runs-on: basic_arm64_100GB
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: |
          ls -l
          echo "Hello World ${{ github.event.inputs.myinput }}"
